resolver: https://raw.githubusercontent.com/input-output-hk/cardano-prelude/0c5b0a6619fadf22f4d62a12154e181a6d035c1c/snapshot.yaml
compiler: ghc-8.6.5

allow-newer: true

packages:
  - cardano-db
  - cardano-db/test
  - cardano-db-sync
  - cardano-db-sync-extended

flags:
  # Bundle VRF crypto in libsodium and do not rely on an external fork to have it.
  # This still requires the host system to have the 'standard' libsodium installed.
  cardano-crypto-praos:
    external-libsodium-vrf: false

ghc-options:
  cardano-db:               -Wall -Werror -fwarn-redundant-constraints
  cardano-db-test:          -Wall -Werror -fwarn-redundant-constraints
  cardano-db-sync:          -Wall -Werror -fwarn-redundant-constraints
  cardano-db-sync-extended: -Wall -Werror -fwarn-redundant-constraints

extra-deps:

  - binary-0.8.7.0
  - bimap-0.4.0
  - brick-0.47.1
  - config-ini-0.2.4.0
  - containers-0.5.11.0
  - data-clist-0.1.2.3
  - ekg-prometheus-adapter-0.1.0.4
  - esqueleto-3.2.2
  - generic-monoid-0.1.0.0
  - libsystemd-journal-1.4.4
  - network-3.1.1.1
  - snap-core-1.0.4.1
  - snap-server-1.1.1.1
  - persistent-2.10.5.1
  - persistent-postgresql-2.10.1.2
  - persistent-template-2.8.2.3
  - prometheus-2.1.2
  - pvss-0.2.0
  - tasty-hedgehog-1.0.0.2
  - text-zipper-0.10.1
  - time-units-1.0.0
  - word-wrap-0.4.1
  - transformers-except-0.1.1
  - text-ansi-0.1.0
  - Diff-0.4.0
  - katip-0.8.3.0
  - moo-1.2
  - gray-code-0.3.1
  - Unique-0.4.7.6
  - statistics-linreg-0.3
  - socks-0.6.1
  - servant-0.17
  - servant-server-0.17
  - connection-0.3.1
  - http-api-data-0.4.1.1
  - time-compat-1.9.2.2
  - quiet-0.2

  - git: https://github.com/input-output-hk/cardano-crypto
    commit: 2547ad1e80aeabca2899951601079408becbc92c

  - git: https://github.com/input-output-hk/cardano-prelude
    commit: d7a531a8a9f48944299bcdccd3856684dfddce19
    subdirs:
      - .
      - test

  - git: https://github.com/input-output-hk/iohk-monitoring-framework
    commit: d4bb653fcef181befe3883490c66faed46b6197d
    subdirs:
      - contra-tracer
      - iohk-monitoring
      - plugins/backend-aggregation
      - plugins/backend-ekg
      - plugins/backend-monitoring
      - plugins/backend-trace-forwarder
      - plugins/scribe-systemd
      - tracer-transformers

  - git: https://github.com/input-output-hk/cardano-base
    commit: 42a31449d68150ea89663c61727745f9448e0590
    subdirs:
      - binary
      - cardano-crypto-praos
      - binary/test
      - cardano-crypto-class
      - slotting

  - git: https://github.com/input-output-hk/goblins
    commit: cde90a2b27f79187ca8310b6549331e59595e7ba

  - git: https://github.com/input-output-hk/cardano-ledger-specs
    commit: d5eaac6c4b21a8e69dc3a5503a72e3c3bfde648e
    subdirs:
      - byron/crypto
      - byron/crypto/test
      - byron/chain/executable-spec
      - byron/ledger/executable-spec
      - byron/ledger/impl
      - byron/ledger/impl/test
      - semantics/executable-spec
      - shelley/chain-and-ledger/dependencies/non-integer
      - shelley/chain-and-ledger/executable-spec
      - shelley/chain-and-ledger/executable-spec/test

  - git: https://github.com/input-output-hk/ouroboros-network
    commit: 6a2b8922856460cccdc7015d33a14ebd28696d14
    subdirs:
      - cardano-client
      - io-sim
      - io-sim-classes
      - network-mux
      - ouroboros-network
      - ouroboros-network-framework
      - Win32-network
      - ouroboros-consensus
      - ouroboros-consensus-byron
      - ouroboros-consensus-byronspec
      - ouroboros-consensus-shelley
      - ouroboros-consensus-cardano
      - typed-protocols
      - typed-protocols-examples
      - ouroboros-network-testing
      - ouroboros-consensus/ouroboros-consensus-mock
      - ouroboros-consensus/ouroboros-consensus-test-infra

  - git: https://github.com/input-output-hk/cardano-node
    commit: 4f44b01f190030dd56f40edb462a2addb6df4061
    subdirs:
      - cardano-config

flags:
  # Bundle VRF crypto in libsodium and do not rely on an external fork to have it.
  # This still requires the host system to have the 'standard' libsodium installed.
  cardano-crypto-praos:
    external-libsodium-vrf: false


nix:
  pure: true
  packages: [ zlib.dev, zlib.out
            , openssl.dev, openssl.out
            , haskell.compiler.ghc865
            , pkg-config
            , systemd.dev
            , postgresql
            ]
